apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildnest-ecommerce-blue
  labels:
    app: buildnest-ecommerce
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buildnest-ecommerce
      version: blue
  template:
    metadata:
      labels:
        app: buildnest-ecommerce
        version: blue
    spec:
      containers:
        - name: buildnest-ecommerce
          image: buildnest-ecommerce:blue
          ports:
            - containerPort: 8080
