apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildnest-ecommerce-green
  labels:
    app: buildnest-ecommerce
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buildnest-ecommerce
      version: green
  template:
    metadata:
      labels:
        app: buildnest-ecommerce
        version: green
    spec:
      containers:
        - name: buildnest-ecommerce
          image: buildnest-ecommerce:green
          ports:
            - containerPort: 8080
