apiVersion: v1
kind: Secret
metadata:
  name: buildnest-ecommerce-secrets
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME"
  SPRING_DATASOURCE_USERNAME: "CHANGE_ME"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  RAZORPAY_KEY_ID: "CHANGE_ME"
  RAZORPAY_KEY_SECRET: "CHANGE_ME"
  ELASTICSEARCH_USERNAME: "elastic"
  ELASTICSEARCH_PASSWORD: "CHANGE_ME"
