apiVersion: v1
kind: Service
metadata:
  name: buildnest-ecommerce
  labels:
    app: buildnest-ecommerce
spec:
  type: ClusterIP
  selector:
    app: buildnest-ecommerce
  ports:
    - name: http
      port: 80
      targetPort: 8080
