apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildnest-ecommerce
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: buildnest-ecommerce
          image: buildnest-ecommerce:staging
